apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.29.2   # new version
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: nginx-staging
      previewService: nginx-staging-preview
      autoPromotionEnabled: true

